{% set name = "antiberty" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/antiberty-{{ version }}.tar.gz
  sha256: 899a401e8b0ef9586d27713b4867aa26149ec0b63387d0be55164f458b6c3bad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=1.7.1
    - transformers >=4.5.1

test:
  imports:
    - antiberty
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  license: MIT
  license_file: LICENSE.MD
  license_family: MIT
  home: https://github.com/jeffreyruffolo/AntiBERTy
  summary: Antibody-specific masked language model
  description: |
    Official repository for AntiBERTy, an antibody-specific transformer language model pre-trained on
    558M natural antibody sequences, as described in https://arxiv.org/abs/2112.07782.

extra:
  recipe-maintainers:
    - mbestipa
